remote_theme: pmarsceill/just-the-docs

title: DeviantArt Filter
email: rthaut@gmail.com
description: >-
  Have you ever want to block/filter deviations (a.k.a. submissions) while browsing DeviantArt? Well now you can! Simply install DeviantArt Filter in your web browser of choice and start filtering by user and/or keyword.
baseurl: "/deviantART-Filter"
url: "https://rthaut.github.io"
plugins:
  - jekyll-feed
  - jekyll-remote-theme

ga_tracking:

# Just the Docs theme configuration
color_scheme: deviantart
logo:
aux_links:
  # "DeviantArt Filter on DeviantArt":
  #   - "https://fav.me/d6uocct"
  # "DeviantArt Filter on GitHub":
  #   - "https://github.com/rthaut/deviantART-Filter"
  "Get for Google Chrome":
    - "https://chrome.google.com/webstore/detail/deviantart-filter/odlmamilbohnpnoomjclomghphbajikp"
  "Get for Mozilla Firefox":
    - "https://addons.mozilla.org/en-US/firefox/addon/deviantart-filter/"
heading_anchors: true
footer_content: "&lt;/&gt; <a href=\"https://github.com/rthaut/deviantART-Filter\">Source code available on GitHub</a>"
